version: "3.7"
services:
  calculator_web:
    image: calculator-web:dev
    container_name: calculatorweb
    build:
      context: ./aspnetapp
      dockerfile: Dockerfile
    ports:
      - "51789:80"
    environment:
      - ADMIN_API_URL=http://calculatorapi
    networks: 
      - webnet
  calculatorapi:
    image: calculator-api:dev
    container_name: calculatorapi
    build:
      context: ./nodeapp
      dockerfile: Dockerfile
    ports:
      - "51790:80"
    networks:
      - webnet
networks:
   webnet:
